/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/linker/ng_module_factory';
import * as import1 from '../../src/j3components.module';
import * as import2 from '@angular/common/src/common_module';
import * as import3 from '../../src/accordion/accordion.module';
import * as import4 from '../../src/syntax-highlighter/syntax-highlighter.module';
import * as import5 from '@angular/common/src/localization';
import * as import6 from '@angular/core/src/di/injector';
import * as import7 from '@angular/core/src/i18n/tokens';
class J3ComponentsModuleInjector extends import0.NgModuleInjector<import1.J3ComponentsModule> {
  _CommonModule_0:import2.CommonModule;
  _AccordionModule_1:import3.AccordionModule;
  _SyntaxHighlighterModule_2:import4.SyntaxHighlighterModule;
  _J3ComponentsModule_3:import1.J3ComponentsModule;
  __NgLocalization_4:import5.NgLocaleLocalization;
  constructor(parent:import6.Injector) {
    super(parent,([] as any[]),([] as any[]));
  }
  get _NgLocalization_4():import5.NgLocaleLocalization {
    if ((this.__NgLocalization_4 == null)) { (this.__NgLocalization_4 = new import5.NgLocaleLocalization(this.parent.get(import7.LOCALE_ID))); }
    return this.__NgLocalization_4;
  }
  createInternal():import1.J3ComponentsModule {
    this._CommonModule_0 = new import2.CommonModule();
    this._AccordionModule_1 = new import3.AccordionModule();
    this._SyntaxHighlighterModule_2 = new import4.SyntaxHighlighterModule();
    this._J3ComponentsModule_3 = new import1.J3ComponentsModule();
    return this._J3ComponentsModule_3;
  }
  getInternal(token:any,notFoundResult:any):any {
    if ((token === import2.CommonModule)) { return this._CommonModule_0; }
    if ((token === import3.AccordionModule)) { return this._AccordionModule_1; }
    if ((token === import4.SyntaxHighlighterModule)) { return this._SyntaxHighlighterModule_2; }
    if ((token === import1.J3ComponentsModule)) { return this._J3ComponentsModule_3; }
    if ((token === import5.NgLocalization)) { return this._NgLocalization_4; }
    return notFoundResult;
  }
  destroyInternal():void {
  }
}
export const J3ComponentsModuleNgFactory:import0.NgModuleFactory<import1.J3ComponentsModule> = new import0.NgModuleFactory(J3ComponentsModuleInjector,import1.J3ComponentsModule);